### ISSUE TITLE
Unable to Deploy Server Node

### ISSUE THREAD

**Issue by ryancasler** [Mimiix/node-red-contrib-deconz#73]
After setting up the server node, I click deploy and this is what I get:
![image](https://user-images.githubusercontent.com/30270489/78505796-ccc1f980-7743-11ea-8216-5dca3146065f.png)

This is my setup.

![image](https://user-images.githubusercontent.com/30270489/78505816-e4997d80-7743-11ea-86b8-a64369fd25f3.png)

I am running deconz service on alternate ports since I am also running a DIYHue server on the same device as my conbee.  But I confirmed that the settings are correct. I can access the Phoscon app at the HTTP port specified.  And the ws port is what my service for deconz is specified to use.

ExecStart=/usr/bin/deCONZ -platform minimal --http-port=8000 --upnp=0 --ws-port=8081

Clicking on Get Settings does absolutely nothing.  No prompt, no popup, no errors.

Oh...there is also nothing at all in the debug window.  When I go to uninstall the Deconz package from the palette there is a red triangle next to "Object"

In the terminal window I see this:
5 Apr 18:44:46 - [info] Waiting for missing types to be registered:
5 Apr 18:44:46 - [info]  - deconz-server
5 Apr 18:45:24 - [info] Stopping flows
5 Apr 18:45:24 - [info] Stopped flows

When installing, I get the following error:
5 Apr 18:27:34 - [info] Installed module: node-red-contrib-deconz
5 Apr 18:27:39 - [info] Added node types:
5 Apr 18:27:39 - [info]  - node-red-contrib-deconz:deconz-input
5 Apr 18:27:39 - [info]  - node-red-contrib-deconz:deconz-get
5 Apr 18:27:39 - [info]  - node-red-contrib-deconz:deconz-output : SyntaxError:                                   Unexpected token }
5 Apr 18:27:39 - [info]  - node-red-contrib-deconz:deconz-event
5 Apr 18:27:39 - [info]  - node-red-contrib-deconz:deconz-battery
5 Apr 18:27:39 - [info]  - node-red-contrib-deconz:deconz-server : SyntaxError:                                   Unexpected token }

And in the event log in Node-Red, I get this error when installing:
```
2020-04-05T17:58:55.885Z Install : node-red-contrib-deconz 1.1.13

2020-04-05T17:58:56.410Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-deconz@1.1.13
2020-04-05T17:59:46.099Z [err] npm
2020-04-05T17:59:46.102Z [err]  
2020-04-05T17:59:46.104Z [err] WARN
2020-04-05T17:59:46.114Z [err]  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2020-04-05T18:00:18.760Z [out] 
2020-04-05T18:00:18.760Z [out] > bcrypt@3.0.6 install /home/pi/.node-red/node_modules/bcrypt
2020-04-05T18:00:18.760Z [out] > node-pre-gyp install --fallback-to-build
2020-04-05T18:00:18.760Z [out] 
2020-04-05T18:00:20.402Z [err] /home/pi/.node-red/node_modules/nopt/lib/nopt.js:1
2020-04-05T18:00:20.402Z [err] t attributes to use.
2020-04-05T18:00:20.402Z [err]   ^^^^^^^^^^
2020-04-05T18:00:20.402Z [err] 
2020-04-05T18:00:20.402Z [err] SyntaxError: Unexpected identifier
2020-04-05T18:00:20.402Z [err]     at Module._compile (internal/modules/cjs/loader.js:723:23)
2020-04-05T18:00:20.402Z [err]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-04-05T18:00:20.402Z [err]     at Module.load (internal/modules/cjs/loader.js:653:32)
2020-04-05T18:00:20.402Z [err]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-04-05T18:00:20.402Z [err]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2020-04-05T18:00:20.402Z [err]     at Module.require (internal/modules/cjs/loader.js:692:17)
2020-04-05T18:00:20.402Z [err]     at require (internal/modules/cjs/helpers.js:25:18)
2020-04-05T18:00:20.402Z [err]     at Object.<anonymous> (/home/pi/.node-red/node_modules/node-pre-gyp/lib/node-pre-gyp.js:15:12)
2020-04-05T18:00:20.402Z [err]     at Module._compile (internal/modules/cjs/loader.js:778:30)
2020-04-05T18:00:20.402Z [err]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-04-05T18:00:32.671Z [err] npm
2020-04-05T18:00:32.673Z [err]  
2020-04-05T18:00:32.676Z [err] WARN
2020-04-05T18:00:32.678Z [err]  multiple-select@1.5.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
2020-04-05T18:00:32.681Z [err] npm
2020-04-05T18:00:32.684Z [err]  WARN
2020-04-05T18:00:32.686Z [err]  node-red-project@0.0.1 No repository field.
2020-04-05T18:00:32.694Z [err] npm WARN node-red-project@0.0.1 No license field.
2020-04-05T18:00:32.697Z [err] npm
2020-04-05T18:00:32.699Z [err]  
2020-04-05T18:00:32.701Z [err] WARN
2020-04-05T18:00:32.714Z [err]  optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@3.0.6 (node_modules/bcrypt):
2020-04-05T18:00:32.714Z [err] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@3.0.6 install: `node-pre-gyp install --fallback-to-build`
2020-04-05T18:00:32.714Z [err] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
2020-04-05T18:00:32.714Z [err] 
2020-04-05T18:00:32.748Z [out] + node-red-contrib-deconz@1.1.13
2020-04-05T18:00:32.748Z [out] added 7 packages from 14 contributors in 84.841s
2020-04-05T18:00:39.723Z [out] 
2020-04-05T18:00:39.723Z [out] 2 packages are looking for funding
2020-04-05T18:00:39.723Z [out]   run `npm fund` for details
2020-04-05T18:00:39.723Z [out] 
2020-04-05T18:00:41.108Z rc=0
```

**Comment by andreypopov** [comment]
try to re-install,
5 Apr 18:27:39 - [info] - node-red-contrib-deconz:deconz-output : SyntaxError: Unexpected token }
5 Apr 18:27:39 - [info] - node-red-contrib-deconz:deconz-event
5 Apr 18:27:39 - [info] - node-red-contrib-deconz:deconz-battery
5 Apr 18:27:39 - [info] - node-red-contrib-deconz:deconz-server : SyntaxError: Unexpected token }

seems like files were broken..

version of node-red?

**Comment by ryancasler** [comment]
I was trying on an RPi ZeroW.  It worked correctly on my RPi3. It's version 1.0.4 on both of them.

**Comment by Zehir** [comment]
This seems to be solved, if not please open the issue again.
